// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjVSWfK-KRoao5ddtVI4pLzas9xyMEx4A',
    appId: '1:1069629988518:web:71e35c703dce796e419e67',
    messagingSenderId: '1069629988518',
    projectId: 'smart-parking-5eff5',
    authDomain: 'smart-parking-5eff5.firebaseapp.com',
    storageBucket: 'smart-parking-5eff5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg34FjqNnogbuS8-0iOkipZ8fSYsFW0HA',
    appId: '1:1069629988518:android:a1592db0956fe634419e67',
    messagingSenderId: '1069629988518',
    projectId: 'smart-parking-5eff5',
    storageBucket: 'smart-parking-5eff5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvmc48hHraRr7IICmkWr7HvW0yDaz-tpw',
    appId: '1:1069629988518:ios:e39584b4c3acde7d419e67',
    messagingSenderId: '1069629988518',
    projectId: 'smart-parking-5eff5',
    storageBucket: 'smart-parking-5eff5.appspot.com',
    iosClientId: '1069629988518-6r35da8t8rr2queeid0rpjp0qhi648m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvmc48hHraRr7IICmkWr7HvW0yDaz-tpw',
    appId: '1:1069629988518:ios:800b4235d0eb2533419e67',
    messagingSenderId: '1069629988518',
    projectId: 'smart-parking-5eff5',
    storageBucket: 'smart-parking-5eff5.appspot.com',
    iosClientId: '1069629988518-p7dhh8dk7jiko213qmn7mf505nlnfsev.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoapp.RunnerTests',
  );
}
