// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg34FjqNnogbuS8-0iOkipZ8fSYsFW0HA',
    appId: '1:1069629988518:android:729915254ce86c47419e67',
    messagingSenderId: '1069629988518',
    projectId: 'smart-parking-5eff5',
    databaseURL: 'https://smart-parking-5eff5-default-rtdb.firebaseio.com',
    storageBucket: 'smart-parking-5eff5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvmc48hHraRr7IICmkWr7HvW0yDaz-tpw',
    appId: '1:1069629988518:ios:8c7253385584e172419e67',
    messagingSenderId: '1069629988518',
    projectId: 'smart-parking-5eff5',
    databaseURL: 'https://smart-parking-5eff5-default-rtdb.firebaseio.com',
    storageBucket: 'smart-parking-5eff5.appspot.com',
    iosClientId: '1069629988518-av4d836qq112nl0d57ejejppiav1gp5u.apps.googleusercontent.com',
    iosBundleId: 'com.graduationproject.graduation.graduation',
  );
}
